app:
  debug: true
  host: "127.0.0.1"
  port: 8080

applog:
  log_format: "%(asctime)s %(service_name)s %(env_type)s %(levelname)s: %(message)s"
  handlers:
    stream:
      handler: 'stdout'
  level: 'DEBUG'

mongo:
  uri: "mongodb+srv://root:zfwaK8RxbJ4gZvP@twokeepcom.ioxf2fy.mongodb.net/"
  database: "onetotwo"
